unit Configurator;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, Menus, ExtCtrls, StdCtrls, ComCtrls;

type
  TFormConfigurator = class(TForm)
    MenuSetting: TMainMenu;
    MenuFile: TMenuItem;
    MenuSaveConfiguration: TMenuItem;
    MenuLoadSettings: TMenuItem;
    PanelWindowRuleteName: TPanel;
    EditWindowRuleteName: TEdit;
    LabelWindowRulete: TLabel;
    LabelWindowRuleteName: TLabel;
    EditWindowRuleteNameSizeX: TEdit;
    LabelWindowRuleteNameSizeX: TLabel;
    EditWindowRuleteNameSizeY: TEdit;
    LabelWindowRuleteNameSizeY: TLabel;
    PanelWindowRuleteNameScan: TPanel;
    PageControlConfigurator: TPageControl;
    TabSheetClicker: TTabSheet;
    PageControlClicker: TPageControl;
    TabSheetGlobal: TTabSheet;
    TabSheetCloseWindows: TTabSheet;
    TabSheetHashNumber: TTabSheet;
    TabSheetPair: TTabSheet;
    TabSheetColumn: TTabSheet;
    TabSheetDozen: TTabSheet;
    TabSheetNumber: TTabSheet;
    TabSheetSixline: TTabSheet;
    TabSheetStreet: TTabSheet;
    TabSheetAngle: TTabSheet;
    LabelWindowRuleteNameDiscription: TLabel;
    EditPairLowPosX: TEdit;
    LabelPairLow: TLabel;
    LabelPairLowPosX: TLabel;
    LabelPairLowPosY: TLabel;
    EditPairLowPosY: TEdit;
    PanelPairLowPosScan: TPanel;
    LabelPairHighPosX: TLabel;
    EditPairHighPosX: TEdit;
    LabelPairHighPosY: TLabel;
    EditPairHighPosY: TEdit;
    PanelPairHighPosScan: TPanel;
    LabelPairHigh: TLabel;
    LabelPairOddPosX: TLabel;
    EditPairOddPosX: TEdit;
    LabelPairOddPosY: TLabel;
    EditPairOddPosY: TEdit;
    PanelPairOddPosScan: TPanel;
    LabelPairOdd: TLabel;
    EditPairEvenPosX: TEdit;
    LabelPairEven: TLabel;
    LabelPairEvenPosX: TLabel;
    LabelPairEvenPosY: TLabel;
    EditPairEvenPosY: TEdit;
    PanelPairEvenPosScan: TPanel;
    LabelPairRedPosX: TLabel;
    EditPairRedPosX: TEdit;
    LabelPairRedPosY: TLabel;
    EditPairRedPosY: TEdit;
    PanelPairRedPosScan: TPanel;
    LabelPairRed: TLabel;
    LabelPairBlackPosX: TLabel;
    EditPairBlackPosX: TEdit;
    LabelPairBlackPosY: TLabel;
    EditPairBlackPosY: TEdit;
    PanelPairBlackPosScan: TPanel;
    LabelPairBlack: TLabel;
    EditColumn2To11PosX: TEdit;
    LabelColumn2To11: TLabel;
    LabelColumn2To11PosX: TLabel;
    LabelColumn2To11PosY: TLabel;
    EditColumn2To11PosY: TEdit;
    PanelColumn2To11PosScan: TPanel;
    LabelColumn2To12PosX: TLabel;
    EditColumn2To12PosX: TEdit;
    LabelColumn2To12PosY: TLabel;
    EditColumn2To12PosY: TEdit;
    PanelColumn2To12PosScan: TPanel;
    LabelColumn2To12: TLabel;
    LabelColumn2To13PosX: TLabel;
    EditColumn2To13PosX: TEdit;
    LabelColumn2To13PosY: TLabel;
    EditColumn2To13PosY: TEdit;
    PanelColumn2To13PosScan: TPanel;
    LabelColumn2To13: TLabel;
    EditDozen1st12PosX: TEdit;
    LabelDozen1st12: TLabel;
    LabelDozen1st12PosX: TLabel;
    LabelDozen1st12PosY: TLabel;
    EditDozen1st12PosY: TEdit;
    PanelDozen1st12PosScan: TPanel;
    LabelDozen2st12PosX: TLabel;
    EditDozen2st12PosX: TEdit;
    LabelDozen2st12PosY: TLabel;
    EditDozen2st12PosY: TEdit;
    PanelDozen2st12PosScan: TPanel;
    LabelDozen2st12: TLabel;
    LabelDozen3st12PosX: TLabel;
    EditDozen3st12PosX: TEdit;
    LabelDozen3st12PosY: TLabel;
    EditDozen3st12PosY: TEdit;
    PanelDozen3st12PosScan: TPanel;
    LabelDozen3st12: TLabel;
    EditNumber1PosX: TEdit;
    LabelNumber1: TLabel;
    LabelNumber1PosX: TLabel;
    LabelNumber1PosY: TLabel;
    EditNumber1PosY: TEdit;
    EditNumber1PosScan: TPanel;
    LabelNumber2PosX: TLabel;
    EditNumber2PosX: TEdit;
    LabelNumber2PosY: TLabel;
    EditNumber2PosY: TEdit;
    EditNumber2PosScan: TPanel;
    LabelNumber2: TLabel;
    LabelNumber3PosX: TLabel;
    EditNumber3PosX: TEdit;
    LabelNumber3PosY: TLabel;
    EditNumber3PosY: TEdit;
    EditNumber3PosScan: TPanel;
    LabelNumber3: TLabel;
    EditNumber4PosX: TEdit;
    LabelNumber4: TLabel;
    LabelNumber4PosX: TLabel;
    LabelNumber4PosY: TLabel;
    EditNumber4PosY: TEdit;
    EditNumber4PosScan: TPanel;
    LabelNumber5PosX: TLabel;
    EditNumber5PosX: TEdit;
    LabelNumber5PosY: TLabel;
    EditNumber5PosY: TEdit;
    EditNumber5PosScan: TPanel;
    LabelNumber5: TLabel;
    LabelNumber6PosX: TLabel;
    EditNumber6PosX: TEdit;
    LabelNumber6PosY: TLabel;
    EditNumber6PosY: TEdit;
    EditNumber6PosScan: TPanel;
    LabelNumber6: TLabel;
    EditNumber0PosX: TEdit;
    LabelNumber0: TLabel;
    LabelNumber0PosX: TLabel;
    LabelNumber0PosY: TLabel;
    EditNumber0PosY: TEdit;
    EditNumber0PosScan: TPanel;
    EditNumber7PosX: TEdit;
    LabelNumber7: TLabel;
    LabelNumber7PosX: TLabel;
    LabelNumber7PosY: TLabel;
    EditNumber7PosY: TEdit;
    EditNumber7PosScan: TPanel;
    LabelNumber8PosX: TLabel;
    EditNumber8PosX: TEdit;
    LabelNumber8PosY: TLabel;
    EditNumber8PosY: TEdit;
    EditNumber8PosScan: TPanel;
    LabelNumber8: TLabel;
    LabelNumber9PosX: TLabel;
    EditNumber9PosX: TEdit;
    LabelNumber9PosY: TLabel;
    EditNumber9PosY: TEdit;
    EditNumber9PosScan: TPanel;
    LabelNumber9: TLabel;
    EditNumber11PosX: TEdit;
    LabelNumber11: TLabel;
    LabelNumber11PosX: TLabel;
    LabelNumber11PosY: TLabel;
    EditNumber11PosY: TEdit;
    EditNumber11PosScan: TPanel;
    LabelNumber12PosX: TLabel;
    EditNumber12PosX: TEdit;
    LabelNumber12PosY: TLabel;
    EditNumber12PosY: TEdit;
    EditNumber12PosScan: TPanel;
    LabelNumber12: TLabel;
    LabelNumber13PosX: TLabel;
    EditNumber13PosX: TEdit;
    LabelNumber13PosY: TLabel;
    EditNumber13PosY: TEdit;
    EditNumber13PosScan: TPanel;
    LabelNumber13: TLabel;
    EditNumber14PosX: TEdit;
    LabelNumber14: TLabel;
    LabelNumber14PosX: TLabel;
    LabelNumber14PosY: TLabel;
    EditNumber14PosY: TEdit;
    EditNumber14PosScan: TPanel;
    LabelNumber15PosX: TLabel;
    EditNumber15PosX: TEdit;
    LabelNumber15PosY: TLabel;
    EditNumber15PosY: TEdit;
    EditNumber15PosScan: TPanel;
    LabelNumber15: TLabel;
    LabelNumber16PosX: TLabel;
    EditNumber16PosX: TEdit;
    LabelNumber16PosY: TLabel;
    EditNumber16PosY: TEdit;
    EditNumber16PosScan: TPanel;
    LabelNumber16: TLabel;
    EditNumber10PosX: TEdit;
    LabelNumber10: TLabel;
    LabelNumber10PosX: TLabel;
    LabelNumber10PosY: TLabel;
    EditNumber10PosY: TEdit;
    EditNumber10PosScan: TPanel;
    EditNumber17PosX: TEdit;
    LabelNumber17: TLabel;
    LabelNumber17PosX: TLabel;
    LabelNumber17PosY: TLabel;
    EditNumber17PosY: TEdit;
    EditNumber17PosScan: TPanel;
    LabelNumber18PosX: TLabel;
    EditNumber18PosX: TEdit;
    LabelNumber18PosY: TLabel;
    EditNumber18PosY: TEdit;
    EditNumber18PosScan: TPanel;
    LabelNumber18: TLabel;
    LabelNumber19PosX: TLabel;
    EditNumber19PosX: TEdit;
    LabelNumber19PosY: TLabel;
    EditNumber19PosY: TEdit;
    EditNumber19PosScan: TPanel;
    LabelNumber19: TLabel;
    EditNumber21PosX: TEdit;
    LabelNumber21: TLabel;
    LabelNumber21PosX: TLabel;
    LabelNumber21PosY: TLabel;
    EditNumber21PosY: TEdit;
    EditNumber21PosScan: TPanel;
    LabelNumber22PosX: TLabel;
    EditNumber22PosX: TEdit;
    LabelNumber22PosY: TLabel;
    EditNumber22PosY: TEdit;
    EditNumber22PosScan: TPanel;
    LabelNumber22: TLabel;
    LabelNumber23PosX: TLabel;
    EditNumber23PosX: TEdit;
    LabelNumber23PosY: TLabel;
    EditNumber23PosY: TEdit;
    EditNumber23PosScan: TPanel;
    LabelNumber23: TLabel;
    EditNumber24PosX: TEdit;
    LabelNumber24: TLabel;
    LabelNumber24PosX: TLabel;
    LabelNumber24PosY: TLabel;
    EditNumber24PosY: TEdit;
    EditNumber24PosScan: TPanel;
    LabelNumber25PosX: TLabel;
    EditNumber25PosX: TEdit;
    LabelNumber25PosY: TLabel;
    EditNumber25PosY: TEdit;
    EditNumber25PosScan: TPanel;
    LabelNumber25: TLabel;
    LabelNumber26PosX: TLabel;
    EditNumber26PosX: TEdit;
    LabelNumber26PosY: TLabel;
    EditNumber26PosY: TEdit;
    EditNumber26PosScan: TPanel;
    LabelNumber26: TLabel;
    EditNumber20PosX: TEdit;
    LabelNumber20: TLabel;
    LabelNumber20PosX: TLabel;
    LabelNumber20PosY: TLabel;
    EditNumber20PosY: TEdit;
    EditNumber20PosScan: TPanel;
    EditNumber27PosX: TEdit;
    LabelNumber27: TLabel;
    LabelNumber27PosX: TLabel;
    LabelNumber27PosY: TLabel;
    EditNumber27PosY: TEdit;
    EditNumber27PosScan: TPanel;
    LabelNumber28PosX: TLabel;
    EditNumber28PosX: TEdit;
    LabelNumber28PosY: TLabel;
    EditNumber28PosY: TEdit;
    EditNumber28PosScan: TPanel;
    LabelNumber28: TLabel;
    LabelNumber29PosX: TLabel;
    EditNumber29PosX: TEdit;
    LabelNumber29PosY: TLabel;
    EditNumber29PosY: TEdit;
    EditNumber29PosScan: TPanel;
    LabelNumber29: TLabel;
    EditNumber31PosX: TEdit;
    LabelNumber31: TLabel;
    LabelNumber31PosX: TLabel;
    LabelNumber31PosY: TLabel;
    EditNumber31PosY: TEdit;
    EditNumber31PosScan: TPanel;
    LabelNumber32PosX: TLabel;
    EditNumber32PosX: TEdit;
    LabelNumber32PosY: TLabel;
    EditNumber32PosY: TEdit;
    EditNumber32PosScan: TPanel;
    LabelNumber32: TLabel;
    LabelNumber33PosX: TLabel;
    EditNumber33PosX: TEdit;
    LabelNumber33PosY: TLabel;
    EditNumber33PosY: TEdit;
    EditNumber33PosScan: TPanel;
    LabelNumber33: TLabel;
    EditNumber34PosX: TEdit;
    LabelNumber34: TLabel;
    LabelNumber34PosX: TLabel;
    LabelNumber34PosY: TLabel;
    EditNumber34PosY: TEdit;
    EditNumber34PosScan: TPanel;
    LabelNumber35PosX: TLabel;
    EditNumber35PosX: TEdit;
    LabelNumber35PosY: TLabel;
    EditNumber35PosY: TEdit;
    EditNumber35PosScan: TPanel;
    LabelNumber35: TLabel;
    LabelNumber36PosX: TLabel;
    EditNumber36PosX: TEdit;
    LabelNumber36PosY: TLabel;
    EditNumber36PosY: TEdit;
    EditNumber36PosScan: TPanel;
    LabelNumber36: TLabel;
    EditNumber30PosX: TEdit;
    LabelNumber30: TLabel;
    LabelNumber30PosX: TLabel;
    LabelNumber30PosY: TLabel;
    EditNumber30PosY: TEdit;
    EditNumber30PosScan: TPanel;
    EditSixline1PosX: TEdit;
    LabelSixline1: TLabel;
    LabelSixline1PosX: TLabel;
    LabelSixline1PosY: TLabel;
    EditSixline1PosY: TEdit;
    PanelSixline1PosScan: TPanel;
    LabelSixline2PosX: TLabel;
    EditSixline2PosX: TEdit;
    LabelSixline2PosY: TLabel;
    EditSixline2PosY: TEdit;
    PanelSixline2PosScan: TPanel;
    LabelSixline2: TLabel;
    LabelSixline3PosX: TLabel;
    EditSixline3PosX: TEdit;
    LabelSixline3PosY: TLabel;
    EditSixline3PosY: TEdit;
    PanelSixline3PosScan: TPanel;
    LabelSixline3: TLabel;
    EditSixline4PosX: TEdit;
    LabelSixline4: TLabel;
    LabelSixline4PosX: TLabel;
    LabelSixline4PosY: TLabel;
    EditSixline4PosY: TEdit;
    PanelSixline4PosScan: TPanel;
    LabelSixline5PosX: TLabel;
    EditSixline5PosX: TEdit;
    LabelSixline5PosY: TLabel;
    EditSixline5PosY: TEdit;
    PanelSixline5PosScan: TPanel;
    LabelSixline5: TLabel;
    LabelSixline6PosX: TLabel;
    EditSixline6PosX: TEdit;
    LabelSixline6PosY: TLabel;
    EditSixline6PosY: TEdit;
    PanelSixline6PosScan: TPanel;
    LabelSixline6: TLabel;
    EditSixline7PosX: TEdit;
    LabelSixline7: TLabel;
    LabelSixline7PosX: TLabel;
    LabelSixline7PosY: TLabel;
    EditSixline7PosY: TEdit;
    PanelSixline7PosScan: TPanel;
    LabelSixline8PosX: TLabel;
    EditSixline8PosX: TEdit;
    LabelSixline8PosY: TLabel;
    EditSixline8PosY: TEdit;
    PanelSixline8PosScan: TPanel;
    LabelSixline8: TLabel;
    LabelSixline9PosX: TLabel;
    EditSixline9PosX: TEdit;
    LabelSixline9PosY: TLabel;
    EditSixline9PosY: TEdit;
    PanelSixline9PosScan: TPanel;
    LabelSixline9: TLabel;
    EditSixline11PosX: TEdit;
    LabelSixline11: TLabel;
    LabelSixline11PosX: TLabel;
    LabelSixline11PosY: TLabel;
    EditSixline11PosY: TEdit;
    PanelSixline11PosScan: TPanel;
    EditSixline10PosX: TEdit;
    LabelSixline10: TLabel;
    LabelSixline10PosX: TLabel;
    LabelSixline10PosY: TLabel;
    EditSixline10PosY: TEdit;
    PanelSixline10PosScan: TPanel;
    EditStreet1PosX: TEdit;
    LabelStreet1: TLabel;
    LabelStreet1PosX: TLabel;
    LabelStreet1PosY: TLabel;
    EditStreet1PosY: TEdit;
    PanelStreet1PosScan: TPanel;
    LabelStreet2PosX: TLabel;
    EditStreet2PosX: TEdit;
    LabelStreet2PosY: TLabel;
    EditStreet2PosY: TEdit;
    PanelStreet2PosScan: TPanel;
    LabelStreet2: TLabel;
    LabelStreet3PosX: TLabel;
    EditStreet3PosX: TEdit;
    LabelStreet3PosY: TLabel;
    EditStreet3PosY: TEdit;
    PanelStreet3PosScan: TPanel;
    LabelStreet3: TLabel;
    EditStreet4PosX: TEdit;
    LabelStreet4: TLabel;
    LabelStreet4PosX: TLabel;
    LabelStreet4PosY: TLabel;
    EditStreet4PosY: TEdit;
    PanelStreet4PosScan: TPanel;
    LabelStreet5PosX: TLabel;
    EditStreet5PosX: TEdit;
    LabelStreet5PosY: TLabel;
    EditStreet5PosY: TEdit;
    PanelStreet5PosScan: TPanel;
    LabelStreet5: TLabel;
    LabelStreet6PosX: TLabel;
    EditStreet6PosX: TEdit;
    LabelStreet6PosY: TLabel;
    EditStreet6PosY: TEdit;
    PanelStreet6PosScan: TPanel;
    LabelStreet6: TLabel;
    EditStreet0PosX: TEdit;
    LabelStreet0: TLabel;
    LabelStreet0PosX: TLabel;
    LabelStreet0PosY: TLabel;
    EditStreet0PosY: TEdit;
    PanelStreet0PosScan: TPanel;
    EditStreet7PosX: TEdit;
    LabelStreet7: TLabel;
    LabelStreet7PosX: TLabel;
    LabelStreet7PosY: TLabel;
    EditStreet7PosY: TEdit;
    PanelStreet7PosScan: TPanel;
    LabelStreet8PosX: TLabel;
    EditStreet8PosX: TEdit;
    LabelStreet8PosY: TLabel;
    EditStreet8PosY: TEdit;
    PanelStreet8PosScan: TPanel;
    LabelStreet8: TLabel;
    LabelStreet9PosX: TLabel;
    EditStreet9PosX: TEdit;
    LabelStreet9PosY: TLabel;
    EditStreet9PosY: TEdit;
    PanelStreet9PosScan: TPanel;
    LabelStreet9: TLabel;
    EditStreet11PosX: TEdit;
    LabelStreet11: TLabel;
    LabelStreet11PosX: TLabel;
    LabelStreet11PosY: TLabel;
    EditStreet11PosY: TEdit;
    PanelStreet11PosScan: TPanel;
    LabelStreet12PosX: TLabel;
    EditStreet12PosX: TEdit;
    LabelStreet12PosY: TLabel;
    EditStreet12PosY: TEdit;
    PanelStreet12PosScan: TPanel;
    LabelStreet12: TLabel;
    LabelStreet13PosX: TLabel;
    EditStreet13PosX: TEdit;
    LabelStreet13PosY: TLabel;
    EditStreet13PosY: TEdit;
    PanelStreet13PosScan: TPanel;
    LabelStreet13: TLabel;
    EditStreet10PosX: TEdit;
    LabelStreet10: TLabel;
    LabelStreet10PosX: TLabel;
    LabelStreet10PosY: TLabel;
    EditStreet10PosY: TEdit;
    PanelStreet10PosScan: TPanel;
    EditAngle1PosX: TEdit;
    LabelAngle1: TLabel;
    LabelAngle1PosX: TLabel;
    LabelAngle1PosY: TLabel;
    EditAngle1PosY: TEdit;
    PanelAngle1PosScan: TPanel;
    LabelAngle2PosX: TLabel;
    EditAngle2PosX: TEdit;
    LabelAngle2PosY: TLabel;
    EditAngle2PosY: TEdit;
    PanelAngle2PosScan: TPanel;
    LabelAngle2: TLabel;
    LabelAngle3PosX: TLabel;
    EditAngle3PosX: TEdit;
    LabelAngle3PosY: TLabel;
    EditAngle3PosY: TEdit;
    PanelAngle3PosScan: TPanel;
    LabelAngle3: TLabel;
    EditAngle4PosX: TEdit;
    LabelAngle4: TLabel;
    LabelAngle4PosX: TLabel;
    LabelAngle4PosY: TLabel;
    EditAngle4PosY: TEdit;
    PanelAngle4PosScan: TPanel;
    LabelAngle5PosX: TLabel;
    EditAngle5PosX: TEdit;
    LabelAngle5PosY: TLabel;
    EditAngle5PosY: TEdit;
    PanelAngle5PosScan: TPanel;
    LabelAngle5: TLabel;
    LabelAngle6PosX: TLabel;
    EditAngle6PosX: TEdit;
    LabelAngle6PosY: TLabel;
    EditAngle6PosY: TEdit;
    PanelAngle6PosScan: TPanel;
    LabelAngle6: TLabel;
    EditAngle0PosX: TEdit;
    LabelAngle0: TLabel;
    LabelAngle0PosX: TLabel;
    LabelAngle0PosY: TLabel;
    EditAngle0PosY: TEdit;
    PanelAngle0PosScan: TPanel;
    EditAngle7PosX: TEdit;
    LabelAngle7: TLabel;
    LabelAngle7PosX: TLabel;
    LabelAngle7PosY: TLabel;
    EditAngle7PosY: TEdit;
    PanelAngle7PosScan: TPanel;
    LabelAngle8PosX: TLabel;
    EditAngle8PosX: TEdit;
    LabelAngle8PosY: TLabel;
    EditAngle8PosY: TEdit;
    PanelAngle8PosScan: TPanel;
    LabelAngle8: TLabel;
    LabelAngle9PosX: TLabel;
    EditAngle9PosX: TEdit;
    LabelAngle9PosY: TLabel;
    EditAngle9PosY: TEdit;
    PanelAngle9PosScan: TPanel;
    LabelAngle9: TLabel;
    EditAngle11PosX: TEdit;
    LabelAngle11: TLabel;
    LabelAngle11PosX: TLabel;
    LabelAngle11PosY: TLabel;
    EditAngle11PosY: TEdit;
    PanelAngle11PosScan: TPanel;
    LabelAngle12PosX: TLabel;
    EditAngle12PosX: TEdit;
    LabelAngle12PosY: TLabel;
    EditAngle12PosY: TEdit;
    PanelAngle12PosScan: TPanel;
    LabelAngle12: TLabel;
    LabelAngle13PosX: TLabel;
    EditAngle13PosX: TEdit;
    LabelAngle13PosY: TLabel;
    EditAngle13PosY: TEdit;
    PanelAngle13PosScan: TPanel;
    LabelAngle13: TLabel;
    EditAngle14PosX: TEdit;
    LabelAngle14: TLabel;
    LabelAngle14PosX: TLabel;
    LabelAngle14PosY: TLabel;
    EditAngle14PosY: TEdit;
    PanelAngle14PosScan: TPanel;
    LabelAngle15PosX: TLabel;
    EditAngle15PosX: TEdit;
    LabelAngle15PosY: TLabel;
    EditAngle15PosY: TEdit;
    PanelAngle15PosScan: TPanel;
    LabelAngle15: TLabel;
    LabelAngle16PosX: TLabel;
    EditAngle16PosX: TEdit;
    LabelAngle16PosY: TLabel;
    EditAngle16PosY: TEdit;
    PanelAngle16PosScan: TPanel;
    LabelAngle16: TLabel;
    EditAngle10PosX: TEdit;
    LabelAngle10: TLabel;
    LabelAngle10PosX: TLabel;
    LabelAngle10PosY: TLabel;
    EditAngle10PosY: TEdit;
    PanelAngle10PosScan: TPanel;
    EditAngle17PosX: TEdit;
    LabelAngle17: TLabel;
    LabelAngle17PosX: TLabel;
    LabelAngle17PosY: TLabel;
    EditAngle17PosY: TEdit;
    PanelAngle17PosScan: TPanel;
    LabelAngle18PosX: TLabel;
    EditAngle18PosX: TEdit;
    LabelAngle18PosY: TLabel;
    EditAngle18PosY: TEdit;
    PanelAngle18PosScan: TPanel;
    LabelAngle18: TLabel;
    LabelAngle19PosX: TLabel;
    EditAngle19PosX: TEdit;
    LabelAngle19PosY: TLabel;
    EditAngle19PosY: TEdit;
    PanelAngle19PosScan: TPanel;
    LabelAngle19: TLabel;
    EditAngle21PosX: TEdit;
    LabelAngle21: TLabel;
    LabelAngle21PosX: TLabel;
    LabelAngle21PosY: TLabel;
    EditAngle21PosY: TEdit;
    PanelAngle21PosScan: TPanel;
    LabelAngle22PosX: TLabel;
    EditAngle22PosX: TEdit;
    LabelAngle22PosY: TLabel;
    EditAngle22PosY: TEdit;
    PanelAngle22PosScan: TPanel;
    LabelAngle22: TLabel;
    EditAngle20PosX: TEdit;
    LabelAngle20: TLabel;
    LabelAngle20PosX: TLabel;
    LabelAngle20PosY: TLabel;
    EditAngle20PosY: TEdit;
    PanelAngle20PosScan: TPanel;
    LabelHashNumberPosX: TLabel;
    EditHashNumberPosX: TEdit;
    LabelHashNumberPosY: TLabel;
    EditHashNumberPosY: TEdit;
    PanelHashNumberPosScan: TPanel;
    LabelHashNumberPos: TLabel;
    LabelHashNumberImg: TLabel;
    PanelHashNumberImgScan: TPanel;
    PanelHashNumberImg: TPanel;
    ImageHashNumberImg: TImage;
    LabelHashNumber0: TLabel;
    PanelHashNumber0Scan: TPanel;
    LabelHashNumber: TLabel;
    EditHashNumber0: TEdit;
    LabelHashNumber1: TLabel;
    PanelHashNumber1Scan: TPanel;
    EditHashNumber1: TEdit;
    LabelHashNumber2: TLabel;
    PanelHashNumber2Scan: TPanel;
    EditHashNumber2: TEdit;
    LabelHashNumber3: TLabel;
    PanelHashNumber3Scan: TPanel;
    EditHashNumber3: TEdit;
    LabelHashNumber4: TLabel;
    PanelHashNumber4Scan: TPanel;
    EditHashNumber4: TEdit;
    LabelHashNumber5: TLabel;
    PanelHashNumber5Scan: TPanel;
    EditHashNumber5: TEdit;
    LabelHashNumber6: TLabel;
    PanelHashNumber6Scan: TPanel;
    EditHashNumber6: TEdit;
    LabelHashNumber7: TLabel;
    PanelHashNumber7Scan: TPanel;
    EditHashNumber7: TEdit;
    LabelHashNumber8: TLabel;
    PanelHashNumber8Scan: TPanel;
    EditHashNumber8: TEdit;
    LabelHashNumber9: TLabel;
    PanelHashNumber9Scan: TPanel;
    EditHashNumber9: TEdit;
    LabelHashNumber10: TLabel;
    PanelHashNumber10Scan: TPanel;
    EditHashNumber10: TEdit;
    LabelHashNumber11: TLabel;
    PanelHashNumber11Scan: TPanel;
    EditHashNumber11: TEdit;
    LabelHashNumber12: TLabel;
    PanelHashNumber12Scan: TPanel;
    EditHashNumber12: TEdit;
    LabelHashNumber13: TLabel;
    PanelHashNumber13Scan: TPanel;
    EditHashNumber13: TEdit;
    LabelHashNumber14: TLabel;
    PanelHashNumber14Scan: TPanel;
    EditHashNumber14: TEdit;
    LabelHashNumber15: TLabel;
    PanelHashNumber15Scan: TPanel;
    EditHashNumber15: TEdit;
    LabelHashNumber16: TLabel;
    PanelHashNumber16Scan: TPanel;
    EditHashNumber16: TEdit;
    LabelHashNumber17: TLabel;
    PanelHashNumber17Scan: TPanel;
    EditHashNumber17: TEdit;
    LabelHashNumber18: TLabel;
    PanelHashNumber18Scan: TPanel;
    EditHashNumber18: TEdit;
    LabelHashNumber19: TLabel;
    PanelHashNumber19Scan: TPanel;
    EditHashNumber19: TEdit;
    LabelHashNumber20: TLabel;
    PanelHashNumber20Scan: TPanel;
    EditHashNumber20: TEdit;
    LabelHashNumber21: TLabel;
    PanelHashNumber21Scan: TPanel;
    EditHashNumber21: TEdit;
    LabelHashNumber22: TLabel;
    PanelHashNumber22Scan: TPanel;
    EditHashNumber22: TEdit;
    LabelHashNumber23: TLabel;
    PanelHashNumber23Scan: TPanel;
    EditHashNumber23: TEdit;
    LabelHashNumber24: TLabel;
    PanelHashNumber24Scan: TPanel;
    EditHashNumber24: TEdit;
    LabelHashNumber25: TLabel;
    PanelHashNumber25Scan: TPanel;
    EditHashNumber25: TEdit;
    LabelHashNumber26: TLabel;
    PanelHashNumber26Scan: TPanel;
    EditHashNumber26: TEdit;
    LabelHashNumber27: TLabel;
    PanelHashNumber27Scan: TPanel;
    EditHashNumber27: TEdit;
    LabelHashNumber28: TLabel;
    PanelHashNumber28Scan: TPanel;
    EditHashNumber28: TEdit;
    LabelHashNumber29: TLabel;
    PanelHashNumber29Scan: TPanel;
    EditHashNumber29: TEdit;
    LabelHashNumber30: TLabel;
    PanelHashNumber30Scan: TPanel;
    EditHashNumber30: TEdit;
    LabelHashNumber31: TLabel;
    PanelHashNumber31Scan: TPanel;
    EditHashNumber31: TEdit;
    LabelHashNumber32: TLabel;
    PanelHashNumber32Scan: TPanel;
    EditHashNumber32: TEdit;
    LabelHashNumber33: TLabel;
    PanelHashNumber33Scan: TPanel;
    EditHashNumber33: TEdit;
    LabelHashNumber34: TLabel;
    PanelHashNumber34Scan: TPanel;
    EditHashNumber34: TEdit;
    LabelHashNumber35: TLabel;
    PanelHashNumber35Scan: TPanel;
    EditHashNumber35: TEdit;
    LabelHashNumber36: TLabel;
    PanelHashNumber36Scan: TPanel;
    EditHashNumber36: TEdit;
    LabelCloseWindows: TLabel;
    PanelCloseWindows1: TPanel;
    LabelCloseWindows1Name: TLabel;
    EditCloseWindows1Name: TEdit;
    LabelCloseWindows1SizeX: TLabel;
    EditCloseWindows1SizeX: TEdit;
    LabelCloseWindows1SizeY: TLabel;
    EditCloseWindows1SizeY: TEdit;
    PanelCloseWindows1SizeScan: TPanel;
    LabelCloseWindows1PosX: TLabel;
    EditCloseWindows1PosX: TEdit;
    LabelCloseWindows1PosY: TLabel;
    EditCloseWindows1PosY: TEdit;
    PanelCloseWindows1PosScan: TPanel;
    LabelCloseWindows1CloseBtn: TLabel;
    PanelCloseWindows2: TPanel;
    LabelCloseWindows2Name: TLabel;
    LabelCloseWindows2SizeX: TLabel;
    LabelCloseWindows2SizeY: TLabel;
    LabelCloseWindows2PosX: TLabel;
    LabelCloseWindows2PosY: TLabel;
    LabelCloseWindows2CloseBtn: TLabel;
    EditCloseWindows2Name: TEdit;
    EditCloseWindows2SizeX: TEdit;
    EditCloseWindows2SizeY: TEdit;
    PanelCloseWindows2SizeScan: TPanel;
    EditCloseWindows2PosX: TEdit;
    EditCloseWindows2PosY: TEdit;
    PanelCloseWindows2PosScan: TPanel;
    PanelCloseWindows3: TPanel;
    LabelCloseWindows3Name: TLabel;
    LabelCloseWindows3SizeX: TLabel;
    LabelCloseWindows3SizeY: TLabel;
    LabelCloseWindows3PosX: TLabel;
    LabelCloseWindows3PosY: TLabel;
    LabelCloseWindows3CloseBtn: TLabel;
    EditCloseWindows3Name: TEdit;
    EditCloseWindows3SizeX: TEdit;
    EditCloseWindows3SizeY: TEdit;
    PanelCloseWindows3SizeScan: TPanel;
    EditCloseWindows3PosX: TEdit;
    EditCloseWindows3PosY: TEdit;
    PanelCloseWindows3PosScan: TPanel;
    PanelCloseWindows4: TPanel;
    LabelCloseWindows4Name: TLabel;
    LabelCloseWindows4SizeX: TLabel;
    LabelCloseWindows4SizeY: TLabel;
    LabelCloseWindows4PosX: TLabel;
    LabelCloseWindows4PosY: TLabel;
    LabelCloseWindows4CloseBtn: TLabel;
    EditCloseWindows4Name: TEdit;
    EditCloseWindows4SizeX: TEdit;
    EditCloseWindows4SizeY: TEdit;
    PanelCloseWindows4SizeScan: TPanel;
    EditCloseWindows4PosX: TEdit;
    EditCloseWindows4PosY: TEdit;
    PanelCloseWindows4PosScan: TPanel;
    PanelCloseWindows5: TPanel;
    LabelCloseWindows5Name: TLabel;
    LabelCloseWindows5SizeX: TLabel;
    LabelCloseWindows5SizeY: TLabel;
    LabelCloseWindows5PosX: TLabel;
    LabelCloseWindows5PosY: TLabel;
    LabelCloseWindows5CloseBtn: TLabel;
    EditCloseWindows5Name: TEdit;
    EditCloseWindows5SizeX: TEdit;
    EditCloseWindows5SizeY: TEdit;
    PanelCloseWindows5SizeScan: TPanel;
    EditCloseWindows5PosX: TEdit;
    EditCloseWindows5PosY: TEdit;
    PanelCloseWindows5PosScan: TPanel;
    PanelCloseWindows6: TPanel;
    LabelCloseWindows6Name: TLabel;
    LabelCloseWindows6SizeX: TLabel;
    LabelCloseWindows6SizeY: TLabel;
    LabelCloseWindows6PosX: TLabel;
    LabelCloseWindows6PosY: TLabel;
    LabelCloseWindows6CloseBtn: TLabel;
    EditCloseWindows6Name: TEdit;
    EditCloseWindows6SizeX: TEdit;
    EditCloseWindows6SizeY: TEdit;
    PanelCloseWindows6SizeScan: TPanel;
    EditCloseWindows6PosX: TEdit;
    EditCloseWindows6PosY: TEdit;
    PanelCloseWindows6PosScan: TPanel;
    LabelBtnSpinPosX: TLabel;
    EditBtnSpinPozX: TEdit;
    LabelBtnSpinPosY: TLabel;
    EditBtnSpinPozY: TEdit;
    PanelBtnSpinScan: TPanel;
    LabelBtnSpin: TLabel;
    LabelBtnSpinImg: TLabel;
    PanelBtnSpinImgScan: TPanel;
    PanelBtnSpinImg: TPanel;
    ImageBtnSpinImg: TImage;
    CheckCloseWindows1Enable: TCheckBox;
    CheckCloseWindows2Enable: TCheckBox;
    CheckCloseWindows3Enable: TCheckBox;
    CheckCloseWindows4Enable: TCheckBox;
    CheckCloseWindows5Enable: TCheckBox;
    CheckCloseWindows6Enable: TCheckBox;
    LabelMousePos: TLabel;
    LabelMousePosX: TLabel;
    LabelMousePosY: TLabel;
    TimerPosMouse: TTimer;
    EditBtnSpinHash: TEdit;
    PanelBtnSpinHashScan: TPanel;
    LabelBtnSpinHash: TLabel;
    SaveConfigurationDialog: TSaveDialog;
    OpenConfigurationDialog: TOpenDialog;
    procedure TimerPosMouseTimer(Sender: TObject);
    procedure PanelWindowRuleteNameScanClick(Sender: TObject);
    procedure FormKeyPress(Sender: TObject; var Key: Char);
    procedure MenuSaveConfigurationClick(Sender: TObject);
    procedure MenuLoadSettingsClick(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

type
  TSize = record
    X: String[6];
    Y: String[6];
end;

type
  TPos = record
    X: String[6];
    Y: String[6];
end;

type
  TWindowRulete = record
    Name: String[255];
    Size: TSize;
end;

type
  TBtnSpin = record
    Pos: TPos;
    Hash: String[20];
end;

type
  TCloseWindow = record
    Enable: BOOL;
    Name: String[255];
    Size: TSize;
    Pos: TPos;
end;

type
  THashNumber = record
    Pos: TPos;
    Hash: array [0..36] of String[20];
end;

type
  TFileConfiguration = record
    WindowRulete: TWindowRulete;
    BtnSpin: TBtnSpin;
    CloseWindows: array [0..9] of TCloseWindow;
    HashNumber: THashNumber;
    PairLowHighPos: array [0..1] of TPos;
    PairOddEvenPos: array [0..1] of TPos;
    PairRedBlackPos: array [0..1] of TPos;
    Column: array [0..2] of TPos;
    Dozen: array [0..2] of TPos;
    Number: array [0..36] of TPos;
    Sixline: array [0..10] of TPos;
    Street: array [0..13] of TPos;
    Angle: array [0..22] of TPos;
end;


var
  strTypeBtnScan: string;
  FormConfigurator: TFormConfigurator;

implementation

{$R *.dfm}

function getWindowRulet():THandle;
var
  R: TRect;
  HWnd : THandle;
  tmpStr : PChar;
  N : Integer;
begin
  HWnd := WindowFromPoint(Mouse.CursorPos);
  N := GetWindowTextLength(HWnd);
  tmpStr := StrAlloc(N + 1);
  GetWindowText(HWnd, tmpStr, N + 1);
  FormConfigurator.EditWindowRuleteName.Text := tmpStr;
  GetWindowREct(HWnd,R);
  FormConfigurator.EditWindowRuleteNameSizeX.Text := IntToStr(R.Right - R.Left);
  FormConfigurator.EditWindowRuleteNameSizeY.Text := IntToStr(R.Bottom - R.Top);

  getWindowRulet := HWnd;
end;


procedure TFormConfigurator.TimerPosMouseTimer(Sender: TObject);
begin
  LabelMousePosX.Caption := 'X: ' + IntToStr(Mouse.CursorPos.X);
  LabelMousePosY.Caption := 'Y: ' + IntToStr(Mouse.CursorPos.Y);

  if strTypeBtnScan = 'ScanWindowRulet' then begin
    getWindowRulet();
  end;
end;

procedure TFormConfigurator.FormKeyPress(Sender: TObject; var Key: Char);
begin
  if Key = '+' then begin
    if strTypeBtnScan = 'ScanWindowRulet' then begin
      getWindowRulet();
    end;

    strTypeBtnScan := '';
  end;
end;

procedure TFormConfigurator.PanelWindowRuleteNameScanClick(
  Sender: TObject);
begin
  strTypeBtnScan := 'ScanWindowRulet';
end;

procedure TFormConfigurator.MenuSaveConfigurationClick(Sender: TObject);
var
  FConfigFile: File of TFileConfiguration;
  FConfig: TFileConfiguration;
begin
  if SaveConfigurationDialog.Execute then begin
    AssignFile(FConfigFile, SaveConfigurationDialog.FileName);
    Rewrite(FConfigFile);

    FConfig.WindowRulete.Name := EditWindowRuleteName.Text;
    FConfig.WindowRulete.Size.X := EditWindowRuleteNameSizeX.Text;
    FConfig.WindowRulete.Size.Y := EditWindowRuleteNameSizeY.Text;

    FConfig.BtnSpin.Pos.X := EditBtnSpinPozX.Text;
    FConfig.BtnSpin.Pos.Y := EditBtnSpinPozY.Text;
    FConfig.BtnSpin.Hash := EditBtnSpinHash.Text;

    FConfig.CloseWindows[0].Enable := CheckCloseWindows1Enable.Checked;
    FConfig.CloseWindows[0].Name := EditCloseWindows1Name.Text;
    FConfig.CloseWindows[0].Size.X := EditCloseWindows1SizeX.Text;
    FConfig.CloseWindows[0].Size.Y := EditCloseWindows1SizeY.Text;
    FConfig.CloseWindows[0].Pos.X := EditCloseWindows1PosX.Text;
    FConfig.CloseWindows[0].Pos.Y := EditCloseWindows1PosY.Text;

    FConfig.CloseWindows[1].Enable := CheckCloseWindows2Enable.Checked;
    FConfig.CloseWindows[1].Name := EditCloseWindows2Name.Text;
    FConfig.CloseWindows[1].Size.X := EditCloseWindows2SizeX.Text;
    FConfig.CloseWindows[1].Size.Y := EditCloseWindows2SizeY.Text;
    FConfig.CloseWindows[1].Pos.X := EditCloseWindows2PosX.Text;
    FConfig.CloseWindows[1].Pos.Y := EditCloseWindows2PosY.Text;

    FConfig.CloseWindows[2].Enable := CheckCloseWindows3Enable.Checked;
    FConfig.CloseWindows[2].Name := EditCloseWindows3Name.Text;
    FConfig.CloseWindows[2].Size.X := EditCloseWindows3SizeX.Text;
    FConfig.CloseWindows[2].Size.Y := EditCloseWindows3SizeY.Text;
    FConfig.CloseWindows[2].Pos.X := EditCloseWindows3PosX.Text;
    FConfig.CloseWindows[2].Pos.Y := EditCloseWindows3PosY.Text;

    FConfig.CloseWindows[3].Enable := CheckCloseWindows4Enable.Checked;
    FConfig.CloseWindows[3].Name := EditCloseWindows4Name.Text;
    FConfig.CloseWindows[3].Size.X := EditCloseWindows4SizeX.Text;
    FConfig.CloseWindows[3].Size.Y := EditCloseWindows4SizeY.Text;
    FConfig.CloseWindows[3].Pos.X := EditCloseWindows4PosX.Text;
    FConfig.CloseWindows[3].Pos.Y := EditCloseWindows4PosY.Text;

    FConfig.CloseWindows[4].Enable := CheckCloseWindows5Enable.Checked;
    FConfig.CloseWindows[4].Name := EditCloseWindows5Name.Text;
    FConfig.CloseWindows[4].Size.X := EditCloseWindows5SizeX.Text;
    FConfig.CloseWindows[4].Size.Y := EditCloseWindows5SizeY.Text;
    FConfig.CloseWindows[4].Pos.X := EditCloseWindows5PosX.Text;
    FConfig.CloseWindows[4].Pos.Y := EditCloseWindows5PosY.Text;

    FConfig.CloseWindows[5].Enable := CheckCloseWindows6Enable.Checked;
    FConfig.CloseWindows[5].Name := EditCloseWindows6Name.Text;
    FConfig.CloseWindows[5].Size.X := EditCloseWindows6SizeX.Text;
    FConfig.CloseWindows[5].Size.Y := EditCloseWindows6SizeY.Text;
    FConfig.CloseWindows[5].Pos.X := EditCloseWindows6PosX.Text;
    FConfig.CloseWindows[5].Pos.Y := EditCloseWindows6PosY.Text;

    FConfig.HashNumber.Pos.X := EditHashNumberPosX.Text; 
    FConfig.HashNumber.Pos.Y := EditHashNumberPosY.Text;
    FConfig.HashNumber.Hash[0] := EditHashNumber0.Text;
    FConfig.HashNumber.Hash[1] := EditHashNumber1.Text;
    FConfig.HashNumber.Hash[2] := EditHashNumber2.Text;
    FConfig.HashNumber.Hash[3] := EditHashNumber3.Text;
    FConfig.HashNumber.Hash[4] := EditHashNumber4.Text;
    FConfig.HashNumber.Hash[5] := EditHashNumber5.Text;
    FConfig.HashNumber.Hash[6] := EditHashNumber6.Text;
    FConfig.HashNumber.Hash[7] := EditHashNumber7.Text;
    FConfig.HashNumber.Hash[8] := EditHashNumber8.Text;
    FConfig.HashNumber.Hash[9] := EditHashNumber9.Text;
    FConfig.HashNumber.Hash[10] := EditHashNumber10.Text;
    FConfig.HashNumber.Hash[11] := EditHashNumber11.Text;
    FConfig.HashNumber.Hash[12] := EditHashNumber12.Text;
    FConfig.HashNumber.Hash[13] := EditHashNumber13.Text;
    FConfig.HashNumber.Hash[14] := EditHashNumber14.Text;
    FConfig.HashNumber.Hash[15] := EditHashNumber15.Text;
    FConfig.HashNumber.Hash[16] := EditHashNumber16.Text;
    FConfig.HashNumber.Hash[17] := EditHashNumber17.Text;
    FConfig.HashNumber.Hash[18] := EditHashNumber18.Text;
    FConfig.HashNumber.Hash[19] := EditHashNumber19.Text;
    FConfig.HashNumber.Hash[20] := EditHashNumber20.Text;
    FConfig.HashNumber.Hash[21] := EditHashNumber21.Text;
    FConfig.HashNumber.Hash[22] := EditHashNumber22.Text;
    FConfig.HashNumber.Hash[23] := EditHashNumber23.Text;
    FConfig.HashNumber.Hash[24] := EditHashNumber24.Text;
    FConfig.HashNumber.Hash[25] := EditHashNumber25.Text;
    FConfig.HashNumber.Hash[26] := EditHashNumber26.Text;
    FConfig.HashNumber.Hash[27] := EditHashNumber27.Text;
    FConfig.HashNumber.Hash[28] := EditHashNumber28.Text;
    FConfig.HashNumber.Hash[29] := EditHashNumber29.Text;
    FConfig.HashNumber.Hash[30] := EditHashNumber30.Text;
    FConfig.HashNumber.Hash[31] := EditHashNumber31.Text;
    FConfig.HashNumber.Hash[32] := EditHashNumber32.Text;
    FConfig.HashNumber.Hash[33] := EditHashNumber33.Text;
    FConfig.HashNumber.Hash[34] := EditHashNumber34.Text;
    FConfig.HashNumber.Hash[35] := EditHashNumber35.Text;
    FConfig.HashNumber.Hash[36] := EditHashNumber36.Text; 

    FConfig.PairLowHighPos[0].X := EditPairLowPosX.Text;
    FConfig.PairLowHighPos[0].Y := EditPairLowPosY.Text;
    FConfig.PairLowHighPos[1].X := EditPairHighPosX.Text;
    FConfig.PairLowHighPos[1].Y := EditPairHighPosY.Text;

    FConfig.PairOddEvenPos[0].X := EditPairOddPosX.Text;
    FConfig.PairOddEvenPos[0].Y := EditPairOddPosY.Text;
    FConfig.PairOddEvenPos[1].X := EditPairEvenPosX.Text;
    FConfig.PairOddEvenPos[1].Y := EditPairEvenPosY.Text;

    FConfig.PairRedBlackPos[0].X := EditPairRedPosX.Text;
    FConfig.PairRedBlackPos[0].Y := EditPairRedPosY.Text;
    FConfig.PairRedBlackPos[1].X := EditPairBlackPosX.Text;
    FConfig.PairRedBlackPos[1].Y := EditPairBlackPosY.Text;

    FConfig.Column[0].X := EditColumn2To11PosX.Text;
    FConfig.Column[0].Y := EditColumn2To11PosY.Text;
    FConfig.Column[1].X := EditColumn2To12PosX.Text;
    FConfig.Column[1].Y := EditColumn2To12PosY.Text;
    FConfig.Column[2].X := EditColumn2To13PosX.Text;
    FConfig.Column[2].Y := EditColumn2To13PosY.Text;

    FConfig.Dozen[0].X := EditDozen1st12PosX.Text;
    FConfig.Dozen[0].Y := EditDozen1st12PosY.Text;
    FConfig.Dozen[1].X := EditDozen2st12PosX.Text;
    FConfig.Dozen[1].Y := EditDozen2st12PosY.Text;
    FConfig.Dozen[2].X := EditDozen3st12PosX.Text;
    FConfig.Dozen[2].Y := EditDozen3st12PosY.Text;

    FConfig.Number[0].X := EditNumber0PosX.Text;
    FConfig.Number[0].Y := EditNumber0PosY.Text;
    FConfig.Number[1].X := EditNumber1PosX.Text;
    FConfig.Number[1].Y := EditNumber1PosY.Text;
    FConfig.Number[2].X := EditNumber2PosX.Text;
    FConfig.Number[2].Y := EditNumber2PosY.Text;
    FConfig.Number[3].X := EditNumber3PosX.Text;
    FConfig.Number[3].Y := EditNumber3PosY.Text;
    FConfig.Number[4].X := EditNumber4PosX.Text;
    FConfig.Number[4].Y := EditNumber4PosY.Text;
    FConfig.Number[5].X := EditNumber5PosX.Text;
    FConfig.Number[5].Y := EditNumber5PosY.Text;
    FConfig.Number[6].X := EditNumber6PosX.Text;
    FConfig.Number[6].Y := EditNumber6PosY.Text;
    FConfig.Number[7].X := EditNumber7PosX.Text;
    FConfig.Number[7].Y := EditNumber7PosY.Text;
    FConfig.Number[8].X := EditNumber8PosX.Text;
    FConfig.Number[8].Y := EditNumber8PosY.Text;
    FConfig.Number[9].X := EditNumber9PosX.Text;
    FConfig.Number[9].Y := EditNumber9PosY.Text;
    FConfig.Number[10].X := EditNumber10PosX.Text;
    FConfig.Number[10].Y := EditNumber10PosY.Text;
    FConfig.Number[11].X := EditNumber11PosX.Text;
    FConfig.Number[11].Y := EditNumber11PosY.Text;
    FConfig.Number[12].X := EditNumber12PosX.Text;
    FConfig.Number[12].Y := EditNumber12PosY.Text;
    FConfig.Number[13].X := EditNumber13PosX.Text;
    FConfig.Number[13].Y := EditNumber13PosY.Text;
    FConfig.Number[14].X := EditNumber14PosX.Text;
    FConfig.Number[14].Y := EditNumber14PosY.Text;
    FConfig.Number[15].X := EditNumber15PosX.Text;
    FConfig.Number[15].Y := EditNumber15PosY.Text;
    FConfig.Number[16].X := EditNumber16PosX.Text;
    FConfig.Number[16].Y := EditNumber16PosY.Text;
    FConfig.Number[17].X := EditNumber17PosX.Text;
    FConfig.Number[17].Y := EditNumber17PosY.Text;
    FConfig.Number[18].X := EditNumber18PosX.Text;
    FConfig.Number[18].Y := EditNumber18PosY.Text;
    FConfig.Number[19].X := EditNumber19PosX.Text;
    FConfig.Number[19].Y := EditNumber19PosY.Text;
    FConfig.Number[20].X := EditNumber20PosX.Text;
    FConfig.Number[20].Y := EditNumber20PosY.Text;
    FConfig.Number[21].X := EditNumber21PosX.Text;
    FConfig.Number[21].Y := EditNumber21PosY.Text;
    FConfig.Number[22].X := EditNumber22PosX.Text;
    FConfig.Number[22].Y := EditNumber22PosY.Text;
    FConfig.Number[23].X := EditNumber23PosX.Text;
    FConfig.Number[23].Y := EditNumber23PosY.Text;
    FConfig.Number[24].X := EditNumber24PosX.Text;
    FConfig.Number[24].Y := EditNumber24PosY.Text;
    FConfig.Number[25].X := EditNumber25PosX.Text;
    FConfig.Number[25].Y := EditNumber25PosY.Text;
    FConfig.Number[26].X := EditNumber26PosX.Text;
    FConfig.Number[26].Y := EditNumber26PosY.Text;
    FConfig.Number[27].X := EditNumber27PosX.Text;
    FConfig.Number[27].Y := EditNumber27PosY.Text;
    FConfig.Number[28].X := EditNumber28PosX.Text;
    FConfig.Number[28].Y := EditNumber28PosY.Text;
    FConfig.Number[29].X := EditNumber29PosX.Text;
    FConfig.Number[29].Y := EditNumber29PosY.Text;
    FConfig.Number[30].X := EditNumber30PosX.Text;
    FConfig.Number[30].Y := EditNumber30PosY.Text;
    FConfig.Number[31].X := EditNumber31PosX.Text;
    FConfig.Number[31].Y := EditNumber31PosY.Text;
    FConfig.Number[32].X := EditNumber32PosX.Text;
    FConfig.Number[32].Y := EditNumber32PosY.Text;
    FConfig.Number[33].X := EditNumber33PosX.Text;
    FConfig.Number[33].Y := EditNumber33PosY.Text;
    FConfig.Number[34].X := EditNumber34PosX.Text;
    FConfig.Number[34].Y := EditNumber34PosY.Text;
    FConfig.Number[35].X := EditNumber35PosX.Text;
    FConfig.Number[35].Y := EditNumber35PosY.Text;
    FConfig.Number[36].X := EditNumber36PosX.Text;
    FConfig.Number[36].Y := EditNumber36PosY.Text;

    FConfig.Sixline[0].X := EditSixline1PosX.Text;
    FConfig.Sixline[0].Y := EditSixline1PosY.Text;
    FConfig.Sixline[1].X := EditSixline2PosX.Text;
    FConfig.Sixline[1].Y := EditSixline2PosY.Text;
    FConfig.Sixline[2].X := EditSixline3PosX.Text;
    FConfig.Sixline[2].Y := EditSixline3PosY.Text;
    FConfig.Sixline[3].X := EditSixline4PosX.Text;
    FConfig.Sixline[3].Y := EditSixline4PosY.Text;
    FConfig.Sixline[4].X := EditSixline5PosX.Text;
    FConfig.Sixline[4].Y := EditSixline5PosY.Text;
    FConfig.Sixline[5].X := EditSixline6PosX.Text;
    FConfig.Sixline[5].Y := EditSixline6PosY.Text;
    FConfig.Sixline[6].X := EditSixline7PosX.Text;
    FConfig.Sixline[6].Y := EditSixline7PosY.Text;
    FConfig.Sixline[7].X := EditSixline8PosX.Text;
    FConfig.Sixline[7].Y := EditSixline8PosY.Text;
    FConfig.Sixline[8].X := EditSixline9PosX.Text;
    FConfig.Sixline[8].Y := EditSixline9PosY.Text;
    FConfig.Sixline[9].X := EditSixline10PosX.Text;
    FConfig.Sixline[9].Y := EditSixline10PosY.Text;
    FConfig.Sixline[10].X := EditSixline11PosX.Text;
    FConfig.Sixline[10].Y := EditSixline11PosY.Text;

    FConfig.Street[0].X := EditStreet0PosX.Text;
    FConfig.Street[0].Y := EditStreet0PosY.Text;
    FConfig.Street[1].X := EditStreet1PosX.Text;
    FConfig.Street[1].Y := EditStreet1PosY.Text;
    FConfig.Street[2].X := EditStreet2PosX.Text;
    FConfig.Street[2].Y := EditStreet2PosY.Text;
    FConfig.Street[3].X := EditStreet3PosX.Text;
    FConfig.Street[3].Y := EditStreet3PosY.Text;
    FConfig.Street[4].X := EditStreet4PosX.Text;
    FConfig.Street[4].Y := EditStreet4PosY.Text;
    FConfig.Street[5].X := EditStreet5PosX.Text;
    FConfig.Street[5].Y := EditStreet5PosY.Text;
    FConfig.Street[6].X := EditStreet6PosX.Text;
    FConfig.Street[6].Y := EditStreet6PosY.Text;
    FConfig.Street[7].X := EditStreet7PosX.Text;
    FConfig.Street[7].Y := EditStreet7PosY.Text;
    FConfig.Street[8].X := EditStreet8PosX.Text;
    FConfig.Street[8].Y := EditStreet8PosY.Text;
    FConfig.Street[9].X := EditStreet9PosX.Text;
    FConfig.Street[9].Y := EditStreet9PosY.Text;
    FConfig.Street[10].X := EditStreet10PosX.Text;
    FConfig.Street[10].Y := EditStreet10PosY.Text;
    FConfig.Street[11].X := EditStreet11PosX.Text;
    FConfig.Street[11].Y := EditStreet11PosY.Text;
    FConfig.Street[12].X := EditStreet12PosX.Text;
    FConfig.Street[12].Y := EditStreet12PosY.Text;
    FConfig.Street[13].X := EditStreet13PosX.Text;
    FConfig.Street[13].Y := EditStreet13PosY.Text;

    FConfig.Angle[0].X := EditAngle0PosX.Text;
    FConfig.Angle[0].Y := EditAngle0PosY.Text;
    FConfig.Angle[1].X := EditAngle1PosX.Text;
    FConfig.Angle[1].Y := EditAngle1PosY.Text;
    FConfig.Angle[2].X := EditAngle2PosX.Text;
    FConfig.Angle[2].Y := EditAngle2PosY.Text;
    FConfig.Angle[3].X := EditAngle3PosX.Text;
    FConfig.Angle[3].Y := EditAngle3PosY.Text;
    FConfig.Angle[4].X := EditAngle4PosX.Text;
    FConfig.Angle[4].Y := EditAngle4PosY.Text;
    FConfig.Angle[5].X := EditAngle5PosX.Text;
    FConfig.Angle[5].Y := EditAngle5PosY.Text;
    FConfig.Angle[6].X := EditAngle6PosX.Text;
    FConfig.Angle[6].Y := EditAngle6PosY.Text;
    FConfig.Angle[7].X := EditAngle7PosX.Text;
    FConfig.Angle[7].Y := EditAngle7PosY.Text;
    FConfig.Angle[8].X := EditAngle8PosX.Text;
    FConfig.Angle[8].Y := EditAngle8PosY.Text;
    FConfig.Angle[9].X := EditAngle9PosX.Text;
    FConfig.Angle[9].Y := EditAngle9PosY.Text;
    FConfig.Angle[10].X := EditAngle10PosX.Text;
    FConfig.Angle[10].Y := EditAngle10PosY.Text;
    FConfig.Angle[11].X := EditAngle11PosX.Text;
    FConfig.Angle[11].Y := EditAngle11PosY.Text;
    FConfig.Angle[12].X := EditAngle12PosX.Text;
    FConfig.Angle[12].Y := EditAngle12PosY.Text;
    FConfig.Angle[13].X := EditAngle13PosX.Text;
    FConfig.Angle[13].Y := EditAngle13PosY.Text;
    FConfig.Angle[14].X := EditAngle14PosX.Text;
    FConfig.Angle[14].Y := EditAngle14PosY.Text;
    FConfig.Angle[15].X := EditAngle15PosX.Text;
    FConfig.Angle[15].Y := EditAngle15PosY.Text;
    FConfig.Angle[16].X := EditAngle16PosX.Text;
    FConfig.Angle[16].Y := EditAngle16PosY.Text;
    FConfig.Angle[17].X := EditAngle17PosX.Text;
    FConfig.Angle[17].Y := EditAngle17PosY.Text;
    FConfig.Angle[18].X := EditAngle18PosX.Text;
    FConfig.Angle[18].Y := EditAngle18PosY.Text;
    FConfig.Angle[19].X := EditAngle19PosX.Text;
    FConfig.Angle[19].Y := EditAngle19PosY.Text;
    FConfig.Angle[20].X := EditAngle20PosX.Text;
    FConfig.Angle[20].Y := EditAngle20PosY.Text;
    FConfig.Angle[21].X := EditAngle21PosX.Text;
    FConfig.Angle[21].Y := EditAngle21PosY.Text;
    FConfig.Angle[22].X := EditAngle22PosX.Text;
    FConfig.Angle[22].Y := EditAngle22PosY.Text;

    Write(FConfigFile, FConfig);
    CloseFile(FConfigFile);
  end;
end;

procedure TFormConfigurator.MenuLoadSettingsClick(Sender: TObject);
var
  FConfigFile: File of TFileConfiguration;
  FConfig: TFileConfiguration;
begin
  if OpenConfigurationDialog.Execute then begin
    AssignFile(FConfigFile, OpenConfigurationDialog.FileName);
    Reset(FConfigFile);

    while not Eof(FConfigFile) do begin
      Read(FConfigFile, FConfig);
    end;

    EditWindowRuleteName.Text := FConfig.WindowRulete.Name;
    EditWindowRuleteNameSizeX.Text := FConfig.WindowRulete.Size.X;
    EditWindowRuleteNameSizeY.Text := FConfig.WindowRulete.Size.Y;

    EditBtnSpinPozX.Text := FConfig.BtnSpin.Pos.X;
    EditBtnSpinPozY.Text := FConfig.BtnSpin.Pos.Y;
    EditBtnSpinHash.Text := FConfig.BtnSpin.Hash;

    CheckCloseWindows1Enable.Checked := FConfig.CloseWindows[0].Enable;
    EditCloseWindows1Name.Text := FConfig.CloseWindows[0].Name;
    EditCloseWindows1SizeX.Text := FConfig.CloseWindows[0].Size.X;
    EditCloseWindows1SizeY.Text := FConfig.CloseWindows[0].Size.Y;
    EditCloseWindows1PosX.Text := FConfig.CloseWindows[0].Pos.X;
    EditCloseWindows1PosY.Text := FConfig.CloseWindows[0].Pos.Y;

    CheckCloseWindows2Enable.Checked := FConfig.CloseWindows[1].Enable;
    EditCloseWindows2Name.Text := FConfig.CloseWindows[1].Name;
    EditCloseWindows2SizeX.Text := FConfig.CloseWindows[1].Size.X;
    EditCloseWindows2SizeY.Text := FConfig.CloseWindows[1].Size.Y;
    EditCloseWindows2PosX.Text := FConfig.CloseWindows[1].Pos.X;
    EditCloseWindows2PosY.Text := FConfig.CloseWindows[1].Pos.Y;

    CheckCloseWindows3Enable.Checked := FConfig.CloseWindows[2].Enable;
    EditCloseWindows3Name.Text := FConfig.CloseWindows[2].Name;
    EditCloseWindows3SizeX.Text := FConfig.CloseWindows[2].Size.X;
    EditCloseWindows3SizeY.Text := FConfig.CloseWindows[2].Size.Y;
    EditCloseWindows3PosX.Text := FConfig.CloseWindows[2].Pos.X;
    EditCloseWindows3PosY.Text := FConfig.CloseWindows[2].Pos.Y;

    CheckCloseWindows4Enable.Checked := FConfig.CloseWindows[3].Enable;
    EditCloseWindows4Name.Text := FConfig.CloseWindows[3].Name;
    EditCloseWindows4SizeX.Text := FConfig.CloseWindows[3].Size.X;
    EditCloseWindows4SizeY.Text := FConfig.CloseWindows[3].Size.Y;
    EditCloseWindows4PosX.Text := FConfig.CloseWindows[3].Pos.X;
    EditCloseWindows4PosY.Text := FConfig.CloseWindows[3].Pos.Y;

    CheckCloseWindows5Enable.Checked := FConfig.CloseWindows[4].Enable;
    EditCloseWindows5Name.Text := FConfig.CloseWindows[4].Name;
    EditCloseWindows5SizeX.Text := FConfig.CloseWindows[4].Size.X;
    EditCloseWindows5SizeY.Text := FConfig.CloseWindows[4].Size.Y;
    EditCloseWindows5PosX.Text := FConfig.CloseWindows[4].Pos.X;
    EditCloseWindows5PosY.Text := FConfig.CloseWindows[4].Pos.Y;

    CheckCloseWindows6Enable.Checked := FConfig.CloseWindows[5].Enable;
    EditCloseWindows6Name.Text := FConfig.CloseWindows[5].Name;
    EditCloseWindows6SizeX.Text := FConfig.CloseWindows[5].Size.X;
    EditCloseWindows6SizeY.Text := FConfig.CloseWindows[5].Size.Y;
    EditCloseWindows6PosX.Text := FConfig.CloseWindows[5].Pos.X;
    EditCloseWindows6PosY.Text := FConfig.CloseWindows[5].Pos.Y;

    EditHashNumberPosX.Text := FConfig.HashNumber.Pos.X;
    EditHashNumberPosY.Text := FConfig.HashNumber.Pos.Y;
    EditHashNumber0.Text := FConfig.HashNumber.Hash[0];
    EditHashNumber1.Text := FConfig.HashNumber.Hash[1];
    EditHashNumber2.Text := FConfig.HashNumber.Hash[2];
    EditHashNumber3.Text := FConfig.HashNumber.Hash[3];
    EditHashNumber4.Text := FConfig.HashNumber.Hash[4];
    EditHashNumber5.Text := FConfig.HashNumber.Hash[5];
    EditHashNumber6.Text := FConfig.HashNumber.Hash[6];
    EditHashNumber7.Text := FConfig.HashNumber.Hash[7];
    EditHashNumber8.Text := FConfig.HashNumber.Hash[8];
    EditHashNumber9.Text := FConfig.HashNumber.Hash[9];
    EditHashNumber10.Text := FConfig.HashNumber.Hash[10];
    EditHashNumber11.Text := FConfig.HashNumber.Hash[11];
    EditHashNumber12.Text := FConfig.HashNumber.Hash[12];
    EditHashNumber13.Text := FConfig.HashNumber.Hash[13];
    EditHashNumber14.Text := FConfig.HashNumber.Hash[14];
    EditHashNumber15.Text := FConfig.HashNumber.Hash[15];
    EditHashNumber16.Text := FConfig.HashNumber.Hash[16];
    EditHashNumber17.Text := FConfig.HashNumber.Hash[17];
    EditHashNumber18.Text := FConfig.HashNumber.Hash[18];
    EditHashNumber19.Text := FConfig.HashNumber.Hash[19];
    EditHashNumber20.Text := FConfig.HashNumber.Hash[20];
    EditHashNumber21.Text := FConfig.HashNumber.Hash[21];
    EditHashNumber22.Text := FConfig.HashNumber.Hash[22];
    EditHashNumber23.Text := FConfig.HashNumber.Hash[23];
    EditHashNumber24.Text := FConfig.HashNumber.Hash[24];
    EditHashNumber25.Text := FConfig.HashNumber.Hash[25];
    EditHashNumber26.Text := FConfig.HashNumber.Hash[26];
    EditHashNumber27.Text := FConfig.HashNumber.Hash[27];
    EditHashNumber28.Text := FConfig.HashNumber.Hash[28];
    EditHashNumber29.Text := FConfig.HashNumber.Hash[29];
    EditHashNumber30.Text := FConfig.HashNumber.Hash[30];
    EditHashNumber31.Text := FConfig.HashNumber.Hash[31];
    EditHashNumber32.Text := FConfig.HashNumber.Hash[32];
    EditHashNumber33.Text := FConfig.HashNumber.Hash[33];
    EditHashNumber34.Text := FConfig.HashNumber.Hash[34];
    EditHashNumber35.Text := FConfig.HashNumber.Hash[35];
    EditHashNumber36.Text := FConfig.HashNumber.Hash[36];

    EditPairLowPosX.Text := FConfig.PairLowHighPos[0].X;
    EditPairLowPosY.Text := FConfig.PairLowHighPos[0].Y;
    EditPairHighPosX.Text := FConfig.PairLowHighPos[1].X;
    EditPairHighPosY.Text := FConfig.PairLowHighPos[1].Y;

    EditPairOddPosX.Text := FConfig.PairOddEvenPos[0].X;
    EditPairOddPosY.Text := FConfig.PairOddEvenPos[0].Y;
    EditPairEvenPosX.Text := FConfig.PairOddEvenPos[1].X;
    EditPairEvenPosY.Text := FConfig.PairOddEvenPos[1].Y;

    EditPairRedPosX.Text := FConfig.PairRedBlackPos[0].X;
    EditPairRedPosY.Text := FConfig.PairRedBlackPos[0].Y;
    EditPairBlackPosX.Text := FConfig.PairRedBlackPos[1].X;
    EditPairBlackPosY.Text := FConfig.PairRedBlackPos[1].Y;

    EditColumn2To11PosX.Text := FConfig.Column[0].X;
    EditColumn2To11PosY.Text := FConfig.Column[0].Y;
    EditColumn2To12PosX.Text := FConfig.Column[1].X;
    EditColumn2To12PosY.Text := FConfig.Column[1].Y;
    EditColumn2To13PosX.Text := FConfig.Column[2].X;
    EditColumn2To13PosY.Text := FConfig.Column[2].Y;

    EditDozen1st12PosX.Text := FConfig.Dozen[0].X;
    EditDozen1st12PosY.Text := FConfig.Dozen[0].Y;
    EditDozen2st12PosX.Text := FConfig.Dozen[1].X;
    EditDozen2st12PosY.Text := FConfig.Dozen[1].Y;
    EditDozen3st12PosX.Text := FConfig.Dozen[2].X;
    EditDozen3st12PosY.Text := FConfig.Dozen[2].Y;

    EditNumber0PosX.Text := FConfig.Number[0].X;
    EditNumber0PosY.Text := FConfig.Number[0].Y;
    EditNumber1PosX.Text := FConfig.Number[1].X;
    EditNumber1PosY.Text := FConfig.Number[1].Y;
    EditNumber2PosX.Text := FConfig.Number[2].X;
    EditNumber2PosY.Text := FConfig.Number[2].Y;
    EditNumber3PosX.Text := FConfig.Number[3].X;
    EditNumber3PosY.Text := FConfig.Number[3].Y;
    EditNumber4PosX.Text := FConfig.Number[4].X;
    EditNumber4PosY.Text := FConfig.Number[4].Y;
    EditNumber5PosX.Text := FConfig.Number[5].X;
    EditNumber5PosY.Text := FConfig.Number[5].Y;
    EditNumber6PosX.Text := FConfig.Number[6].X;
    EditNumber6PosY.Text := FConfig.Number[6].Y;
    EditNumber7PosX.Text := FConfig.Number[7].X;
    EditNumber7PosY.Text := FConfig.Number[7].Y;
    EditNumber8PosX.Text := FConfig.Number[8].X;
    EditNumber8PosY.Text := FConfig.Number[8].Y;
    EditNumber9PosX.Text := FConfig.Number[9].X;
    EditNumber9PosY.Text := FConfig.Number[9].Y;
    EditNumber10PosX.Text := FConfig.Number[10].X;
    EditNumber10PosY.Text := FConfig.Number[10].Y;
    EditNumber11PosX.Text := FConfig.Number[11].X;
    EditNumber11PosY.Text := FConfig.Number[11].Y;
    EditNumber12PosX.Text := FConfig.Number[12].X;
    EditNumber12PosY.Text := FConfig.Number[12].Y;
    EditNumber13PosX.Text := FConfig.Number[13].X;
    EditNumber13PosY.Text := FConfig.Number[13].Y;
    EditNumber14PosX.Text := FConfig.Number[14].X;
    EditNumber14PosY.Text := FConfig.Number[14].Y;
    EditNumber15PosX.Text := FConfig.Number[15].X;
    EditNumber15PosY.Text := FConfig.Number[15].Y;
    EditNumber16PosX.Text := FConfig.Number[16].X;
    EditNumber16PosY.Text := FConfig.Number[16].Y;
    EditNumber17PosX.Text := FConfig.Number[17].X;
    EditNumber17PosY.Text := FConfig.Number[17].Y;
    EditNumber18PosX.Text := FConfig.Number[18].X;
    EditNumber18PosY.Text := FConfig.Number[18].Y;
    EditNumber19PosX.Text := FConfig.Number[19].X;
    EditNumber19PosY.Text := FConfig.Number[19].Y;
    EditNumber20PosX.Text := FConfig.Number[20].X;
    EditNumber20PosY.Text := FConfig.Number[20].Y;
    EditNumber21PosX.Text := FConfig.Number[21].X;
    EditNumber21PosY.Text := FConfig.Number[21].Y;
    EditNumber22PosX.Text := FConfig.Number[22].X;
    EditNumber22PosY.Text := FConfig.Number[22].Y;
    EditNumber23PosX.Text := FConfig.Number[23].X;
    EditNumber23PosY.Text := FConfig.Number[23].Y;
    EditNumber24PosX.Text := FConfig.Number[24].X;
    EditNumber24PosY.Text := FConfig.Number[24].Y;
    EditNumber25PosX.Text := FConfig.Number[25].X;
    EditNumber25PosY.Text := FConfig.Number[25].Y;
    EditNumber26PosX.Text := FConfig.Number[26].X;
    EditNumber26PosY.Text := FConfig.Number[26].Y;
    EditNumber27PosX.Text := FConfig.Number[27].X;
    EditNumber27PosY.Text := FConfig.Number[27].Y;
    EditNumber28PosX.Text := FConfig.Number[28].X;
    EditNumber28PosY.Text := FConfig.Number[28].Y;
    EditNumber29PosX.Text := FConfig.Number[29].X;
    EditNumber29PosY.Text := FConfig.Number[29].Y;
    EditNumber30PosX.Text := FConfig.Number[30].X;
    EditNumber30PosY.Text := FConfig.Number[30].Y;
    EditNumber31PosX.Text := FConfig.Number[31].X;
    EditNumber31PosY.Text := FConfig.Number[31].Y;
    EditNumber32PosX.Text := FConfig.Number[32].X;
    EditNumber32PosY.Text := FConfig.Number[32].Y;
    EditNumber33PosX.Text := FConfig.Number[33].X;
    EditNumber33PosY.Text := FConfig.Number[33].Y;
    EditNumber34PosX.Text := FConfig.Number[34].X;
    EditNumber34PosY.Text := FConfig.Number[34].Y;
    EditNumber35PosX.Text := FConfig.Number[35].X;
    EditNumber35PosY.Text := FConfig.Number[35].Y;
    EditNumber36PosX.Text := FConfig.Number[36].X;
    EditNumber36PosY.Text := FConfig.Number[36].Y;

    EditSixline1PosX.Text := FConfig.Sixline[0].X;
    EditSixline1PosY.Text := FConfig.Sixline[0].Y;
    EditSixline2PosX.Text := FConfig.Sixline[1].X;
    EditSixline2PosY.Text := FConfig.Sixline[1].Y;
    EditSixline3PosX.Text := FConfig.Sixline[2].X;
    EditSixline3PosY.Text := FConfig.Sixline[2].Y;
    EditSixline4PosX.Text := FConfig.Sixline[3].X;
    EditSixline4PosY.Text := FConfig.Sixline[3].Y;
    EditSixline5PosX.Text := FConfig.Sixline[4].X;
    EditSixline5PosY.Text := FConfig.Sixline[4].Y;
    EditSixline6PosX.Text := FConfig.Sixline[5].X;
    EditSixline6PosY.Text := FConfig.Sixline[5].Y;
    EditSixline7PosX.Text := FConfig.Sixline[6].X;
    EditSixline7PosY.Text := FConfig.Sixline[6].Y;
    EditSixline8PosX.Text := FConfig.Sixline[7].X;
    EditSixline8PosY.Text := FConfig.Sixline[7].Y;
    EditSixline9PosX.Text := FConfig.Sixline[8].X;
    EditSixline9PosY.Text := FConfig.Sixline[8].Y;
    EditSixline10PosX.Text := FConfig.Sixline[9].X;
    EditSixline10PosY.Text := FConfig.Sixline[9].Y;
    EditSixline11PosX.Text := FConfig.Sixline[10].X;
    EditSixline11PosY.Text := FConfig.Sixline[10].Y;

    EditStreet0PosX.Text := FConfig.Street[0].X;
    EditStreet0PosY.Text := FConfig.Street[0].Y;
    EditStreet1PosX.Text := FConfig.Street[1].X;
    EditStreet1PosY.Text := FConfig.Street[1].Y;
    EditStreet2PosX.Text := FConfig.Street[2].X;
    EditStreet2PosY.Text := FConfig.Street[2].Y;
    EditStreet3PosX.Text := FConfig.Street[3].X;
    EditStreet3PosY.Text := FConfig.Street[3].Y;
    EditStreet4PosX.Text := FConfig.Street[4].X;
    EditStreet4PosY.Text := FConfig.Street[4].Y;
    EditStreet5PosX.Text := FConfig.Street[5].X;
    EditStreet5PosY.Text := FConfig.Street[5].Y;
    EditStreet6PosX.Text := FConfig.Street[6].X;
    EditStreet6PosY.Text := FConfig.Street[6].Y;
    EditStreet7PosX.Text := FConfig.Street[7].X;
    EditStreet7PosY.Text := FConfig.Street[7].Y;
    EditStreet8PosX.Text := FConfig.Street[8].X;
    EditStreet8PosY.Text := FConfig.Street[8].Y;
    EditStreet9PosX.Text := FConfig.Street[9].X;
    EditStreet9PosY.Text := FConfig.Street[9].Y;
    EditStreet10PosX.Text := FConfig.Street[10].X;
    EditStreet10PosY.Text := FConfig.Street[10].Y;
    EditStreet11PosX.Text := FConfig.Street[11].X;
    EditStreet11PosY.Text := FConfig.Street[11].Y;
    EditStreet12PosX.Text := FConfig.Street[12].X;
    EditStreet12PosY.Text := FConfig.Street[12].Y;
    EditStreet13PosX.Text := FConfig.Street[13].X;
    EditStreet13PosY.Text := FConfig.Street[13].Y;

    EditAngle0PosX.Text := FConfig.Angle[0].X;
    EditAngle0PosY.Text := FConfig.Angle[0].Y;
    EditAngle1PosX.Text := FConfig.Angle[1].X;
    EditAngle1PosY.Text := FConfig.Angle[1].Y;
    EditAngle2PosX.Text := FConfig.Angle[2].X;
    EditAngle2PosY.Text := FConfig.Angle[2].Y;
    EditAngle3PosX.Text := FConfig.Angle[3].X;
    EditAngle3PosY.Text := FConfig.Angle[3].Y;
    EditAngle4PosX.Text := FConfig.Angle[4].X;
    EditAngle4PosY.Text := FConfig.Angle[4].Y;
    EditAngle5PosX.Text := FConfig.Angle[5].X;
    EditAngle5PosY.Text := FConfig.Angle[5].Y;
    EditAngle6PosX.Text := FConfig.Angle[6].X;
    EditAngle6PosY.Text := FConfig.Angle[6].Y;
    EditAngle7PosX.Text := FConfig.Angle[7].X;
    EditAngle7PosY.Text := FConfig.Angle[7].Y;
    EditAngle8PosX.Text := FConfig.Angle[8].X;
    EditAngle8PosY.Text := FConfig.Angle[8].Y;
    EditAngle9PosX.Text := FConfig.Angle[9].X;
    EditAngle9PosY.Text := FConfig.Angle[9].Y;
    EditAngle10PosX.Text := FConfig.Angle[10].X;
    EditAngle10PosY.Text := FConfig.Angle[10].Y;
    EditAngle11PosX.Text := FConfig.Angle[11].X;
    EditAngle11PosY.Text := FConfig.Angle[11].Y;
    EditAngle12PosX.Text := FConfig.Angle[12].X;
    EditAngle12PosY.Text := FConfig.Angle[12].Y;
    EditAngle13PosX.Text := FConfig.Angle[13].X;
    EditAngle13PosY.Text := FConfig.Angle[13].Y;
    EditAngle14PosX.Text := FConfig.Angle[14].X;
    EditAngle14PosY.Text := FConfig.Angle[14].Y;
    EditAngle15PosX.Text := FConfig.Angle[15].X;
    EditAngle15PosY.Text := FConfig.Angle[15].Y;
    EditAngle16PosX.Text := FConfig.Angle[16].X;
    EditAngle16PosY.Text := FConfig.Angle[16].Y;
    EditAngle17PosX.Text := FConfig.Angle[17].X;
    EditAngle17PosY.Text := FConfig.Angle[17].Y;
    EditAngle18PosX.Text := FConfig.Angle[18].X;
    EditAngle18PosY.Text := FConfig.Angle[18].Y;
    EditAngle19PosX.Text := FConfig.Angle[19].X;
    EditAngle19PosY.Text := FConfig.Angle[19].Y;
    EditAngle20PosX.Text := FConfig.Angle[20].X;
    EditAngle20PosY.Text := FConfig.Angle[20].Y;
    EditAngle21PosX.Text := FConfig.Angle[21].X;
    EditAngle21PosY.Text := FConfig.Angle[21].Y;
    EditAngle22PosX.Text := FConfig.Angle[22].X;
    EditAngle22PosY.Text := FConfig.Angle[22].Y;

    CloseFile(FConfigFile);
  end;
end;

end.
